branches:
  only:
    - master
    - /^\d+\.(\d+|x)(\.x)?$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - travis_retry npm install
      script:
        - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
        - git config --global user.email "$EMAIL"
        - git config --global user.name "Mojtaba Izadmehr"
        - mkdir -p ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        # - echo $CI_PROJECT_PATH
        # - git clone git@gitlab.com:${CI_PROJECT_PATH}.git
        # - cd ${CI_PROJECT_NAME}
        - yarn install
        - yarn run release
        - git push --no-verify --follow-tags origin master
