branches:
  only:
    - master
    - /^\d+\.(\d+|x)(\.x)?$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      before_install:
        - chmod +x .travis/build.sh
      install:
        - travis_retry npm install
      script:
        - .travis/push.sh
