branches:
  only:
    - master
    - /^\d+\.(\d+|x)(\.x)?$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - travis_retry npm install
      script:
        - npm run release
      after_success:
        - git config --global user.email "$EMAIL"
        - git config --global user.name "Mojtaba Izadmehr"
        - git checkout master
        - git add .
        - git commit --message "Travis build - $TRAVIS_BUILD_NUMBER"
        - git remote add origin https://${GH_TOKEN}@github.com/m-izadmehr/playground.git > /dev/null 2>&1
        - git push --set-upstream origin master
